name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pnpm setup
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
